# Generated by Django 4.2.5 on 2023-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
