# Generated by Django 3.2.5 on 2023-10-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contact_read_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message_envoye',
        ),
    ]
